title: QuickJS Sandbox in Javascript & Typescript
description: A webassembly sandbox to safely execute Javascript inside of Javascript/Typescript applications
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme